### PR TITLE
Fix incorrectly placed cpp keywords

### PR DESCRIPTION
**Pull request by Waqar144**
Reverts some changes from #120

### CODE REVIEW

**Comment by data-man** [comment]
https://en.cppreference.com/w/cpp/keyword
https://docs.microsoft.com/en-us/cpp/cpp/keywords-cpp
https://docs.microsoft.com/en-us/cpp/cpp/fundamental-types-cpp

Please reread them.

**Comment by Waqar144** [comment]
> https://en.cppreference.com/w/cpp/keyword
> https://docs.microsoft.com/en-us/cpp/cpp/keywords-cpp
> https://docs.microsoft.com/en-us/cpp/cpp/fundamental-types-cpp
> 
> Please reread them.

Ok. so what is your point here? Can you instead of providing links get to that directly?

**Comment by data-man** [comment]
Keywords placed in `cpp_keywords`.
It's logical, no?

**Comment by Waqar144** [comment]
> Keywords placed in `cpp_keywords`.
> It's logical, no?

The point of those keywords being in `types` instead of `keywords` is to give them a different color regardless of what documentation says. When i wrote this highlighter and collected all these keywords for all the languages, I used other editors like `vs-code`, `qt-creator` as a reference to how i should do my coloring. This is why `class`, `struct` went into types.

**Comment by data-man** [comment]
> When i wrote this highlighter

Try this snippet in QOwnNotes:
```c++
#include <string>
std::mutex cout_mutex;
std::lock_guard<std::mutex> lock(cout_mutex);
```
Are you sure that `string` and `wstring` are builtins, not types?

-----
Examples:
Github:
```c++
#include <iostream>
#include <utility>
 
template<class T, class U>
auto add(T t, U u) { return t + u; } // the return type is the type of operator+(T, U)
 
// perfect forwarding of a function call must use decltype(auto)
// in case the function it calls returns by reference
template<class F, class... Args>
decltype(auto) PerfectForward(F fun, Args&&... args) 
{ 
    return fun(std::forward<Args>(args)...); 
}
 
template<auto n> // C++17 auto parameter declaration
auto f() -> std::pair<decltype(n), decltype(n)> // auto can't deduce from brace-init-list
{
    return {n, n};
}
 
int main()
{
    auto a = 1 + 2;            // type of a is int
    auto b = add(1, 1.2);      // type of b is double
    static_assert(std::is_same_v<decltype(a), int>);
    static_assert(std::is_same_v<decltype(b), double>);
 
    auto c0 = a;             // type of c0 is int, holding a copy of a
    decltype(auto) c1 = a;   // type of c1 is int, holding a copy of a
    decltype(auto) c2 = (a); // type of c2 is int&, an alias of a
    std::cout << "a, before modification through c2 = " << a << '\n';
    ++c2;
    std::cout << "a, after modification through c2 = " << a << '\n';
 
    auto [v, w] = f<0>(); //structured binding declaration
 
    auto d = {1, 2}; // OK: type of d is std::initializer_list<int>
    auto n = {5};    // OK: type of n is std::initializer_list<int>
//  auto e{1, 2};    // Error as of C++17, std::initializer_list<int> before
    auto m{5};       // OK: type of m is int as of C++17, initializer_list<int> before
//  decltype(auto) z = { 1, 2 } // Error: {1, 2} is not an expression
 
    // auto is commonly used for unnamed types such as the types of lambda expressions
    auto lambda = [](int x) { return x + 3; };
 
//  auto int x; // valid C++98, error as of C++11
//  auto x;     // valid C, error in C++
}
```

Current QOwnNotes:
Screenshot_20200704_165208

**Comment by Waqar144** [comment]
> Try this snippet in QOwnNotes:

> #include <string>
> std::mutex cout_mutex;
> std::lock_guard<std::mutex> lock(cout_mutex);

I just did.

> #include <string> <--- bug here. string shouldn't be highlighted

Are you sure that string and wstring are builtins, not types?

They are types, but in the context of this highlighter they are built-ins. Builtins are stuff.. that are present in the library(The naming here isn't great, i know lol.), of any language. And of course, not all of library is included, only some of it is. 

I fail to understand the point of that github vs QON code snippet example. Mind expanding on it a bit maybe?

**Comment by data-man** [comment]
> I fail to understand the point of that github vs QON code snippet example.

What do you think, Github has good C++ code highlighting?

> Mind expanding on it a bit maybe?

Can you attach a screenshot of the snippet from your QON (before my PR, of course), please?

**Comment by Waqar144** [comment]
> What do you think, Github has good C++ code highlighting?

It is okay-ish, it doesn't do too much and has kept it more simple

> 
> Can you attach a screenshot of the snippet from your QON (before my PR, of course), please?

Here you go:
image

**Comment by data-man** [comment]
Screenshot_20200704_183850

^

**Comment by Waqar144** [comment]
> Screenshot_20200704_183850
> 
> ^

Yes, indeed that keyword was missing and now we have it, thanks to you.

**Comment by data-man** [comment]
Now, `auto` has green color!

**Comment by Waqar144** [comment]
> No, `auto` has green color!

Indeed. I guess for some reason `auto` wasn't being highlighted if it was in paranthesis. I will look into it

**Comment by data-man** [comment]
Also

a

vs

b

**Comment by Waqar144** [comment]
image

template should also be in types

**Comment by data-man** [comment]
I'm tired of arguing with you, do whatever you want.

**Comment by Waqar144** [comment]
https://github.com/pbek/qmarkdowntextedit/pull/121#issuecomment-653752301 is your answer. There is no argument, and if you like them in different colors, change the colors to whatever you want. After all this is not an ide, and i am just trying to color it the way ide's do.

**Pull request merged**
