### PR TITLE
Fix painting if editor viewportMargin.top() is not 0

### PR DESCRIPTION
**Pull request by Waqar144**
This will fix the alignment of line numbers

### CODE REVIEW

**Comment by pbek** [comment]
No crash with when I just use the new library, but don't turn on line numbers.
But now Instant crash at startup with:

```
    ui->noteTextEdit->setLineNumberEnabled(true);
    ui->encryptedNoteTextEdit->setLineNumberEnabled(true);
```

**Comment by pbek** [comment]
```
1   _q_resolveEntryAndCreateLegacyEngine_recursive                                                                                        qfilesystemengine.cpp             138   0x7ffff620c118 
2   QFileSystemEngine::resolveEntryAndCreateLegacyEngine                                                                                  qfilesystemengine.cpp             196   0x7ffff620c72f 
3   QFileInfoPrivate::QFileInfoPrivate                                                                                                    qflags.h                          120   0x7ffff61d74c3 
4   QFileInfo::QFileInfo                                                                                                                  qfileinfo.cpp                     347   0x7ffff61d74c3 
5   QConfFile::fromName                                                                                                                   qsettings.cpp                     204   0x7ffff62307a9 
6   QConfFileSettingsPrivate::QConfFileSettingsPrivate                                                                                    qstringbuilder.h                  147   0x7ffff62355c9 
7   QSettingsPrivate::create                                                                                                              qsettings.cpp                     298   0x7ffff6235c0e 
8   QSettings::QSettings                                                                                                                  qsettings.cpp                     2689  0x7ffff6235c0e 
9   QOwnNotesMarkdownTextEdit::setPaperMargins                                                                                            qownnotesmarkdowntextedit.cpp     310   0x5555557fa049 
10  MainWindow::noteTextEditResize                                                                                                        mainwindow.cpp                    12428 0x555555656ad6 
11  QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<QResizeEvent *>, void, void (MainWindow:: *)(QResizeEvent *)>::call qobjectdefs_impl.h                152   0x55555569600c 
12  QtPrivate::FunctionPointer<void (MainWindow:: *)(QResizeEvent *)>::call<QtPrivate::List<QResizeEvent *>, void>                        qobjectdefs_impl.h                185   0x5555556929c5 
13  QtPrivate::QSlotObject<void (MainWindow:: *)(QResizeEvent *), QtPrivate::List<QResizeEvent *>, void>::impl                            qobjectdefs_impl.h                418   0x55555568da08 
14  QtPrivate::QSlotObjectBase::call                                                                                                      qobjectdefs_impl.h                398   0x7ffff62e270e 
15  doActivate<false>                                                                                                                     qobject.cpp                       3886  0x7ffff62e270e 
16  QOwnNotesMarkdownTextEdit::resize                                                                                                     moc_qownnotesmarkdowntextedit.cpp 169   0x555555ab0dea 
17  QOwnNotesMarkdownTextEdit::resizeEvent                                                                                                qownnotesmarkdowntextedit.cpp     424   0x5555557fa7c3 
18  QWidget::event(QEvent *)                                                                                                                                                      0x7ffff791337f 
19  QFrame::event(QEvent *)                                                                                                                                                       0x7ffff79c3092 
20  QCoreApplicationPrivate::sendThroughObjectEventFilters                                                                                qcoreapplication.cpp              1190  0x7ffff62ab453 
... <More>                                                                                                                                                                                       
```

**Comment by Waqar144** [comment]
> ```
> 1   _q_resolveEntryAndCreateLegacyEngine_recursive                                                                                        qfilesystemengine.cpp             138   0x7ffff620c118 
> 2   QFileSystemEngine::resolveEntryAndCreateLegacyEngine                                                                                  qfilesystemengine.cpp             196   0x7ffff620c72f 
> 3   QFileInfoPrivate::QFileInfoPrivate                                                                                                    qflags.h                          120   0x7ffff61d74c3 
> 4   QFileInfo::QFileInfo                                                                                                                  qfileinfo.cpp                     347   0x7ffff61d74c3 
> 5   QConfFile::fromName                                                                                                                   qsettings.cpp                     204   0x7ffff62307a9 
> 6   QConfFileSettingsPrivate::QConfFileSettingsPrivate                                                                                    qstringbuilder.h                  147   0x7ffff62355c9 
> 7   QSettingsPrivate::create                                                                                                              qsettings.cpp                     298   0x7ffff6235c0e 
> 8   QSettings::QSettings                                                                                                                  qsettings.cpp                     2689  0x7ffff6235c0e 
> 9   QOwnNotesMarkdownTextEdit::setPaperMargins                                                                                            qownnotesmarkdowntextedit.cpp     310   0x5555557fa049 
> 10  MainWindow::noteTextEditResize                                                                                                        mainwindow.cpp                    12428 0x555555656ad6 
> 11  QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<QResizeEvent *>, void, void (MainWindow:: *)(QResizeEvent *)>::call qobjectdefs_impl.h                152   0x55555569600c 
> 12  QtPrivate::FunctionPointer<void (MainWindow:: *)(QResizeEvent *)>::call<QtPrivate::List<QResizeEvent *>, void>                        qobjectdefs_impl.h                185   0x5555556929c5 
> 13  QtPrivate::QSlotObject<void (MainWindow:: *)(QResizeEvent *), QtPrivate::List<QResizeEvent *>, void>::impl                            qobjectdefs_impl.h                418   0x55555568da08 
> 14  QtPrivate::QSlotObjectBase::call                                                                                                      qobjectdefs_impl.h                398   0x7ffff62e270e 
> 15  doActivate<false>                                                                                                                     qobject.cpp                       3886  0x7ffff62e270e 
> 16  QOwnNotesMarkdownTextEdit::resize                                                                                                     moc_qownnotesmarkdowntextedit.cpp 169   0x555555ab0dea 
> 17  QOwnNotesMarkdownTextEdit::resizeEvent                                                                                                qownnotesmarkdowntextedit.cpp     424   0x5555557fa7c3 
> 18  QWidget::event(QEvent *)                                                                                                                                                      0x7ffff791337f 
> 19  QFrame::event(QEvent *)                                                                                                                                                       0x7ffff79c3092 
> 20  QCoreApplicationPrivate::sendThroughObjectEventFilters                                                                                qcoreapplication.cpp              1190  0x7ffff62ab453 
> ... <More>                                                                                                                                                                                       
> ```

Can't see any reason to crash. Can you show the changes in your `setPaperMargins`?

**Comment by pbek** [comment]
That function was called about 3000 (!) times (I added a qDebug() call) and always with a width of -1. Then QON crashes.

**Comment by Waqar144** [comment]
> That function was called about 3000 (!) times (I added a qDebug() call) and always with a width of -1. Then QON crashes.

Which function?

And can you share the changes in setPaperMargins? There must something not right there

**Comment by pbek** [comment]
> Which function?

QOwnNotesMarkdownTextEdit::setPaperMargins 

> And can you share the changes in setPaperMargins? There must something not right there

what changes?

**Comment by Waqar144** [comment]
> what changes?

I guess you didn't change it at all. You need to block signals for "this" inside that function. 

```
QSignalBlocker b(this);
```

**Comment by pbek** [comment]
Ah, sorry. My bad. I didn't thought I need to put that in on the first test already!

**Comment by pbek** [comment]
> This will fix the alignment of line numbers

Still looks off to me:

Screenshot_20210701_084208

> Ah, sorry. My bad. I didn't thought I need to put that in on the first test already!

I'll need to test that later today.

**Comment by pbek** [comment]
> QSignalBlocker b(this);

I added this in QOwnNotesMarkdownTextEdit::setPaperMargins but it didn't change the crashes when I turn on line-numbers (the function is still called 1000s of times).
Only when I disable the whole `connect(ui->noteTextEdit, &QOwnNotesMarkdownTextEdit::resize, this, &MainWindow::noteTextEditResize);` block in the mainwindow.cpp it doesn't crash any more,

**Comment by pbek** [comment]
I also tried this without success:

```cpp
    QSignalBlocker blocker(this);
    QSignalBlocker blocker2(this->viewport());
    QSignalBlocker blocker3(this->parent());
    QSignalBlocker blocker4(this->mainWindow);
```

...as well with blocking in places in the mainwindow.

When I comment out the `setViewportMargins` calls it also works.

**Comment by pbek** [comment]
I found a way to make it not crash. I need to add a `QSignalBlocker blocker(this);` to `QMarkdownTextEdit::updateLineNumberAreaWidth(int)`. I don't seem to need any other blocker.

But with or without the blocker the note edit is cut off on my PC at home when a note is opened.

image

When I then scroll it's "repaired":

**Comment by Waqar144** [comment]
> with or without the blocker the note edit is cut off on my PC at home when a note is opened.

Yes, that is also because of setPaperMargins as it modifies the viewport margins as well.

**Comment by Waqar144** [comment]
> > QSignalBlocker b(this);
> 
> I added this in QOwnNotesMarkdownTextEdit::setPaperMargins but it didn't change the crashes when I turn on line-numbers (the function is still called 1000s of times).
> Only when I disable the whole `connect(ui->noteTextEdit, &QOwnNotesMarkdownTextEdit::resize, this, &MainWindow::noteTextEditResize);` block in the mainwindow.cpp it doesn't crash any more,

Weird, just a signal blocker in setPaperMargins should work 🤔

**Comment by Waqar144** [comment]
> > with or without the blocker the note edit is cut off on my PC at home when a note is opened.
> 
> Yes, that is also because of setPaperMargins as it modifies the viewport margins as well.

We need to adjust the left margin accordingly, 

Something like: lineNumberArea->width() + 10

**Comment by pbek** [comment]
> We need to adjust the left margin accordingly,

where? any why 10?

**Comment by Waqar144** [comment]
> > We need to adjust the left margin accordingly,
> 
> where? any why 10?

In setPaperMargins, and 10 because that is the value already being used

**Comment by Waqar144** [comment]
If there was no setPaperMargins, this would be a lot easier.

**Comment by pbek** [comment]
> In setPaperMargins, and 10 because that is the value already being used

found out myself, and 10 is used when there is no extra margin added. damn not only DFM adds a margin, you can also opt to use the margin of the DFM outside the DFM 😬

**Comment by pbek** [comment]
> If there was no setPaperMargins, this would be a lot easier.

that's all for the DFM and the mode that only uses the margin of the DFM

**Comment by pbek** [comment]
I now add the width of `lineNumberArea()->lineNumAreaWidth();` (isn't that `lineNumAreaWidth` a bit redundant? `width` alone would do fine, wouldn't it?

I now get an extra margin...

image

that goes away after scrolling....

image

**Comment by pbek** [comment]
> that goes away after scrolling....

I guess that's so because you internally didn't add the default 10 left margin of QON, isn't it?

**Comment by pbek** [comment]
I introduced a var `_lineNumberLeftMarginOffset` in `QMarkdownTextEdit` to smuggle the 10 in.

**Comment by pbek** [comment]
I integrated all changes into `develop` of QOwnNotes.

**Comment by pbek** [comment]
@Waqar144, your fixed colors also need fixing...

```cpp
        const QPen currentLine = QColor("#eef067");
        const QPen otherLines = QColor("#a6a6a6");
```

😅

**Comment by Waqar144** [comment]
> I introduced a var `_lineNumberLeftMarginOffset` in `QMarkdownTextEdit` to smuggle the 10 in.

That won't work properly I think. I think we need to save a `QMargin` and not some offset just (if you are supporting Qt < 5.5). Otherwise, this is completely unnecessary, and you can just use `oldMargins.left()` as the offset value.

**Comment by pbek** [comment]
> That won't work properly I think.

I just set the value in QON. I had no issues with it so far. Do you?

> I think we need to save a QMargin and not some offset just (if you are supporting Qt < 5.5). 

I don't care a lot if it looks perfect below Qt 5.5.

> oldMargins.left()

That way?

```cpp
    const int width = _lineNumArea->isLineNumAreaEnabled() ?
           _lineNumArea->sizeHint().width() + oldMargins.left() :
           oldMargins.left();
```

That didn't work for me. The margin got bigger and bigger while scrolling.

**Comment by Waqar144** [comment]
> > If there was no setPaperMargins, this would be a lot easier.
> 
> that's all for the DFM and the mode that only uses the margin of the DFM

It sets margins in the non-DFM case as well, which is why the line number area breaks.

> I now add the width of lineNumberArea()->lineNumAreaWidth(); (isn't that lineNumAreaWidth a bit redundant? width alone would do fine, wouldn't it?

Yes, It would be more or less the same. But calling that method gets a fresh calculated value, while width might return a cached value, not sure though.

> I now get an extra margin..

> I guess that's so because you internally didn't add the default 10 left margin of QON, isn't it?

Yes, I wasn't sure about this extra margin. I think it is either because the "margins" get accumulated and have a value that is larger than what we expect.

I personally would suggest to completely disable line number area in the DFM mode, it is after all distraction free mode.

**Comment by Waqar144** [comment]
Can we not use document margins instead of viewportMargins for DFM mode? or maybe contentMargins?

**Comment by pbek** [comment]
> I personally would suggest to completely disable line number area in the DFM mode, it is after all distraction free mode.

They are disabled. And also in the mode where it behaves like in DFM.

**Comment by pbek** [comment]
> Can we not use document margins instead of viewportMargins for DFM mode? or maybe contentMargins?

I don't want to bother will all that in DFM. I consider line numbers a distraction in DFM.

**Comment by pbek** [comment]
> It sets margins in the non-DFM case as well, which is why the line number area breaks.

Currently nothing breaks for me. Does anything break in QON for you?

**Comment by Waqar144** [comment]
> I just set the value in QON. I had no issues with it so far. Do you?

You won't but someone with < Qt 5.5 might. viewportMargins() return a default constructed `QMargin()` which I guess will be zero.

> That way?
> ```cpp
    const int width = _lineNumArea->isLineNumAreaEnabled() ?
           _lineNumArea->sizeHint().width() + oldMargins.left() :
           oldMargins.left();
> ```

yes, exactly ;)
But yeah, it will accumulate the margins because we are adding in both places. There must be a cleaner way...

**Comment by pbek** [comment]
> You won't but someone with < Qt 5.5 might.

My goal for old Qt versions is just that important features are "usable".

**Comment by Waqar144** [comment]
> Currently nothing breaks for me. Does anything break in QON for you?

Nopes, but the distance between line number area and editor is very annoying.

**Comment by Waqar144** [comment]
> > You won't but someone with < Qt 5.5 might.
> 
> My goal for old Qt versions is just that important features are "usable".

They should just be dropped. Not sure why you are so insistent on supporting abondonware but sure :man_shrugging:

**Comment by pbek** [comment]
> Nopes, but the space between line number area and editor is very annoying.

That distance?

image

It's the same distance than before. I quite like it. 😆 

> Not sure why you are so insistent on supporting abondonware but sure man_shrugging

1) I just want that it still builds and works in "some way". 😁 
2) I'm bad with letting things go. 🤣

**Comment by pbek** [comment]
> It's the same distance than before. I quite like it.

kate has no margin with or without line numbers. QON has a margin without line numbers, I guess we should also keep that with line numbers.

**Comment by Waqar144** [comment]
Yes, But I guess previously I didn't really notice that distance or got used to it.

**Comment by pbek** [comment]
> Yes, But I guess previously I didn't really notice that distance or got used to it.

I took a look at it without margin and it looked strange when you got used to it with margin.
If you want to add a setting to make that margin configurable in QON, please go ahead. 👍🏻

**Pull request merged**
