### PR TITLE
Generate pkgconfig file by qmake

### PR DESCRIPTION
**Pull request by wineee**
pkg-config is a helper tool used when compiling applications and libraries
This patch will automatically generate the .pc file by qmake

### CODE REVIEW

**Comment by pbek** [comment]
@Waqar144, any objections?

**Comment by pbek** [comment]
@Waqar144?

**Comment by Waqar144** [comment]
Sorry missed the notification here somehow. I have little to no idea about pkgconfig, so I will only say if it works we can merge. It's unlikely QON will ever use it, but if someone else wants, why not.

**Comment by pbek** [comment]
I think so too. Thank you both.

**Pull request merged**
