### PR TITLE
some fixes

### PR DESCRIPTION
**Pull request by sandsmark**
not sure if you want all of it, e. g. the formatting changes, but I prefer it this way.

### CODE REVIEW

**Comment by pbek** [comment]
I'm still checking the changes... 😄

**Comment by pbek** [comment]
Maybe I'll revert the styling changes, but beside that it seems to be all right. Thank you. I'm curious  where you used qmarkdowntextedit.

**Comment by sandsmark** [comment]
just used it (the demo application in this repo) for some quick editing of README.md files

**Comment by pbek** [comment]
nice :smile:

**Pull request merged**
