### PR TITLE
Fix crash due to out of bound array access

### PR DESCRIPTION
**Pull request by Waqar144**

### CODE REVIEW

**Comment by Waqar144** [comment]
## Some colors for testing:

```css

color: #0d5572;

color: #05464f;

color: #133a30;

color: #dd0000;

color: #006994;

color: #00aae4;

color: #1e90ff;

color: #0079c1;

color: #3eb489;

color: #50c878;

color: #7851a9;

color: #800020;

color: #ff9966;

color: #ff7538;

color: #9f1d35;

color: #3e8ede;

color: #007fff;

color: #c32148;

color: #39ca74;

color: #933028;

color: #f26b43;

color: #ef5927;

color: #e5e5cc;

color: #0067a5;

color: #023352;

color: #0d5572;

color: #b7504c;

color: #9c3bf3;

color: #0f4c81;

color: #a64ca6;

color: #b7504c;

color: #8d0d0d;

color: #ffa891;

color: #8b0000;

color: #990000;

color: #dfb63f;

color: #e1ae1b;

color: #c6962c;

color: #b18628;

color: #7a3ee8;

color: #819bb4;

color: #2c89c4;

color: #FFEBCD;

color: #FFE4C4;

color: #FFDEAD;

color: #F5DEB3;

color: #DEB887;

color: #D2B48C;

color: #BC8F8F;

color: #F4A460;

color: #DAA520;

color: #CD853F;

color: #D2691E;

color: #8B4513;

color: #A0522D;

color: #A52A2A;

color: #800000;
color: #DCDCDC;
color: #D3D3D3;
color: #C0C0C0;
color: #A9A9A9;
color: #808080;
color: #696969;
color: #778899;
color: #708090;
color: #2F4F4F;
color: gainsboro;
color: #DCDCDC;
color: rgb(220,220,220);
color: lightgray;
color: #D3D3D3;
color: rgb(211,211,211);
color: silver;
color: #C0C0C0;
color: rgb(192,192,192);
color: darkgray;
color: #A9A9A9;
color: rgb(169,169,169);
color: gray;
color: #808080;
color: rgb(128,128,128);
color: dimgray;
color: #696969;
color: rgb(105,105,105);
color: lightslategray;
color: #778899;
color: rgb(119,136,153);
color: slategray;
color: #708090;
color: rgb(112,128,144);
color: darkslategray;
color: #2F4F4F;
color: rgb(47,79,79);
color: black;
color: #000000;
color: rgb(0,0,0);
color: indigo;
color: #4B0082;
color: rgb(75,0,130);
color: teal;
color: #008080;
color: rgb(0,128,128);
color: lawngreen;
color: #7CFC00;
color: rgb(124,252,0);
color: chartreuse;
color: #7FFF00;
color: rgb(127,255,0);
color: limegreen;
color: #32CD32;
color: rgb(50,205,50);
color: lime;
color: #00FF00;
color: rgb(0.255.0);
color: forestgreen;
color: #228B22;
color: rgb(34,139,34);
color: green;
color: #008000;
color: rgb(0,128,0);
color: darkgreen;
color: #006400;
color: rgb(0,100,0);
color: greenyellow;
color: #ADFF2F;
color: rgb(173,255,47);
color: yellowgreen;
color: #9ACD32;
color: rgb(154,205,50);
color: springgreen;
color: #00FF7F;
color: rgb(0,255,127);
color: mediumspringgreen;
color: #00FA9A;
color: rgb(0,250,154);
color: lightgreen;
color: #90EE90;
color: rgb(144,238,144);
color: palegreen;
color: #98FB98;
color: rgb(152,251,152);
color: darkseagreen;
color: #8FBC8F;
color: rgb(143,188,143);
color: mediumseagreen;
color: #3CB371;
color: rgb(60,179,113);
color: seagreen;
color: #2E8B57;
color: rgb(46,139,87);
color: olive;
color: #808000;
color: rgb(128,128,0);
color: darkolivegreen;
color: #556B2F;
color: rgb(85,107,47);
color: olivedrab;
color: #6B8E23;
color: rgb(107,142,35);
```

**Comment by pbek** [comment]
Looks awesome!
One thing I saw was that the numbers of `color: rgb(192,192,192);` are rendered as number. I wonder if it would be better to also render it in the color of the "color".

**Comment by Waqar144** [comment]
> Looks awesome!

> One thing I saw was that the numbers of `color: rgb(192,192,192);` are rendered as number. I wonder if it would be better to also render it in the color of the "color".

That's because they are being highlighted as numbers...

**Comment by pbek** [comment]
> That's because they are being highlighted as numbers...

Yes, that's what I'm talking about. :grin: 
Do we want that? Or do we want to highlight those numbers in the color of the "css color"?

**Comment by Waqar144** [comment]
Done. I was almost about to give it up but then I looked closely and saw that we were wasting some resources and that changing the position of the function will both optimize it and fix the highlighting issue.

**Pull request merged**
