### PR TITLE
Fix links not following schema styles

### PR DESCRIPTION
**Pull request by Waqar144**
#29

Italics and bolds following heading styles, should I change that as well?

### CODE REVIEW

**Comment by pbek** [comment]
Thank you.

> should I change that as well?

sure, if you like

**Comment by Waqar144** [comment]
> Thank you.
> 
> > should I change that as well?
> 
> sure, if you like

Well then don't mind if the bolds and italics are white in the midst of blue headings :rofl:

**Comment by pbek** [comment]
> Well then don't mind if the bolds and italics are white in the midst of blue headings 🤣

no, stop. it's still early here. I read "want me to change the tests as well" 😆

**Comment by Waqar144** [comment]
> > Well then don't mind if the bolds and italics are white in the midst of blue headings rofl
> 
> no, stop. it's still early here. I read "want me to change the tests as well" laughing

:laughing:

**Pull request merged**
