### PR TITLE
Partial code syntax highlighter rewrite

### PR DESCRIPTION
**Pull request by Waqar144**
- Rewrote all languages data
- Added support for builtin library function/ stuff highlighting
- Improved languages data
- Rewrote the parser to use QMultiHash for much better performance
- Added enum for languages to quickly jump to a language rather than use an if else ladder for better performance
- Refactoring and minor fixes
- Added a template for language data submission

### CODE REVIEW

**Comment by pbek** [comment]
An include was broken.

**Comment by msbentley** [comment]
Great, syntax highlighting! Does this only work in the edit mode? Are there plans for it to work eventually in the preview panel also?

**Comment by Waqar144** [comment]
> Great, syntax highlighting! Does this only work in the edit mode? Are there plans for it to work eventually in the preview panel also?

For syntax highlighting to work in preview mode we have two options
- Modify hoedown to include specific tags for syntax highlighting
- Use a `QWebEngineView`(a web browser), with highlight.js/prism 

I don't know about the first one, and it might not be a good idea to mess with hoedown. The second one works pretty nicely. (I have it in my personal build of QON). Only one problem, it's not supported on older Qt versions so including it in the build would likely break everything less than Qt 5.4.

You can read about it here:
pbek/QOwnNotes#1421

and see it in action here:

pbek/QOwnNotes#1474

**Comment by msbentley** [comment]
OK, thanks for the information! Sounds like a tough one to crack... I would be happy to compile from source to get this, but I notice that on my work laptop (ubuntu 18.04 LTS) I still only have Qt 5.3...

**Comment by Waqar144** [comment]
> OK, thanks for the information! Sounds like a tough one to crack... I would be happy to compile from source to get this, but I notice that on my work laptop (ubuntu 18.04 LTS) I still only have Qt 5.3...

see. problems happening already :rofl: 

It's not tough really, the hard part is covered mostly. We just need to have 2 or 3 code paths for it to work correctly on Linux. And we are mostly worried about the memory increase due to this change...

You can get new Qt in two ways.
- Install QtCreator from qt.io (simple and clean way)
- Install from ppa

We don't have any(mandatory) external dependencies outside of Qt so there should be no problems.

**Comment by pbek** [comment]
> You can get new Qt in two ways.

@Waqar144, if you want to fool around with build systems you could create a experimental snap or appimage :grin:

**Comment by Waqar144** [comment]
> > You can get new Qt in two ways.
> 
> @Waqar144, if you want to fool around with build systems you could create an experimental snap or appimage grin

Sounds like a plan. Can we package different versions of Qt in an appimage or the system one is used?

**Comment by pbek** [comment]
An AppImage (or a snap) contains all dependencies, also Qt.

**Pull request merged**
