### PR TITLE
Improved performance

### PR DESCRIPTION
**Pull request by software-made-easy**
Compare a QChar with QChar is faster than QLatin1Char

### CODE REVIEW

**Comment by Waqar144** [comment]
QChar is never directly compared with QLatin1Char. QLatin1Char implicitly converts to a QChar *at compile time* and then compared. So, I doubt there will be any performance improvements at all. 

However, there is one drawback of this patch. A lot of apps and libraries enable `QT_NO_CAST_FROM_ASCII`. For these apps, qmarkdowntextedit will not compile because code like following is not allowed:

- `QChar c = 'x'`
- Qstring l = `"bb"`

**Comment by pbek** [comment]
So "nay", I guess. 😅

**Comment by software-made-easy** [comment]
> QChar is never directly compared with QLatin1Char. QLatin1Char implicitly converts to a QChar _at compile time_ and then compared. So, I doubt there will be any performance improvements at all.

I thought so, but in my test it was faster with QChar than with QLatin1Char.

**Comment by Waqar144** [comment]
> > QChar is never directly compared with QLatin1Char. QLatin1Char implicitly converts to a QChar _at compile time_ and then compared. So, I doubt there will be any performance improvements at all.
> 
> I thought so, but in my test it was faster with QChar than with QLatin1Char.

Do you have this test available somewhere?

**Comment by software-made-easy** [comment]
> Do you have this test available somewhere?

No, but here are the results:


|             	| Run 1   	| Run 2   	| Run 3   	|
|-------------	|---------	|---------	|---------	|
| QChar       	| 1028869 	| 1134501 	| 1083772 	|
| QLatin1Char 	| 1440273 	| 1143473 	| 1383550 	|

The time is given in nanoseconds. It's not much, but it still made a difference how quickly my application starts (a visible one)

**Comment by Waqar144** [comment]
> but it still made a difference how quickly my application starts (a visible one)

That is very odd. Generally speaking, qmarkdowntextedit should have little to no difference in how fast your application starts. Have you profiled your application to be sure that these changes or qmarkdowntextedit is slowing things down?
And if this application is available somewhere, perhaps I can take a look and maybe we can come up with something that improves it for everybody.

Besides that, when you ran your tests did you create an optimized exe? I often forget to do that and end up wasting time comparing debug build's performance.

For this particular case, I created a benchmark to be sure:
```c++
// Compile with: moc test.cpp -o test.moc && g++ -lQt5Core -lQt5Test -O2 -g -I/usr/include/qt test.cpp -o test
#include <QtTest/QTest>
#include <QtCore/QChar>
#include <QtCore/QObject>
#include <QtCore/QVector>
#include <random>

class Test : public QObject {
    Q_OBJECT
private Q_SLOTS:
    static void bench_qlatin1char() {
        std::vector<QChar> chars;
        for (char i = 'A'; i <= 'z'; ++i)
            chars.push_back(QChar(i));
        std::random_shuffle(chars.begin(), chars.end());
        const auto *a = chars.data();
        const int s = (int)chars.size();
        volatile bool c = false;
        QBENCHMARK {
            for (int i = 0; i < s; ++i)
                c = a[i] == QLatin1Char('a');
        }
    }

    static void bench_qchar() {
        std::vector<QChar> chars;
        for (char i = 'A'; i <= 'z'; ++i)
            chars.push_back(QChar(i));
        std::random_shuffle(chars.begin(), chars.end());
        const auto *a = chars.data();
        const int s = (int)chars.size();

        volatile bool c = false;
        QBENCHMARK {
            for (int i = 0; i < s; ++i)
                c = a[i] == QChar('a');
        }
    }
};
QTEST_MAIN(Test)
#include "test.moc"
```
Results are exactly the same:
```
Config: Using QtTest library 5.15.5, Qt 5.15.5 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 12.1.0)
PASS   : Test::initTestCase()
PASS   : Test::bench_qlatin1char()
RESULT : Test::bench_qlatin1char():
     0.000022 msecs per iteration (total: 94, iterations: 4194304)
PASS   : Test::bench_qchar()
RESULT : Test::bench_qchar():
     0.000022 msecs per iteration (total: 94, iterations: 4194304)
```

**Comment by software-made-easy** [comment]
> Have you profiled your application to be sure that these changes or qmarkdowntextedit is slowing things down? 

Not yet, I will take care of it.

> And if this application is available somewhere, perhaps I can take a look and maybe we can come up with something that improves it for everybody.

If you want to and have nothing else to do <https://github.com/software-made-easy/MarkdownEdit>

> Besides that, when you ran your tests did you create an optimized exe? I often forget to do that and end up wasting time comparing debug build's performance.

I have the build mode in Qt Creator set to "Release".

> For this particular case, I created a benchmark to be sure:

I tested your benchmark and got the same values, strange because when I replaced in qmarkdowntextedit "== QLatin1String" and "!= QLatin1String"
with "== QChar" and "!= QChar" it was still faster. Don't know what could be the reason (tested everything in release mode).

**Comment by Waqar144** [comment]
Just tried, the app's startup is instant so imo it's already doing pretty great. Is there a special case where it's slower?

**Comment by software-made-easy** [comment]
> Just tried, the app's startup is instant so imo it's already doing pretty great. 

Nice to hear, thanks.

> Is there a special case where it's slower?

There are even 2:
  - If you have enchant-2 (enchant version 2) installed and spell check is enabled
  - If you have the app installed and try to open a large file (haven't figured out how to load files when the app finishes loading app (no problems in the gui) yet)

**Pull request closed without merging**
