### PR TITLE
Line number area update

### PR DESCRIPTION
**Pull request by Waqar144**

### CODE REVIEW

**Comment by Waqar144** [comment]
@pbek 

Can you test now? You will need to block signals in `setPaperMargins` for `this`.

```cpp
QSignalBlocker b(this);
```

Some more changes will be needed, i.e.,
- the viewport width set in `setPaperMargins` now needs to care about line number area width as well. This can be done by `lineNumberArea()->sizeHint.width()`;
- For distraction free mode, line number will need to be disabled probably (if it is active) and renabled on leaving distraction free mode.

For basic testing, changes only to the `setPaperMargins` is needed. We can then add a setting and use that enable and disable Line Numbers right from within the constructor of `QOwnNotesMardownTextEdit`

**Comment by pbek** [comment]
Thank you! I'll test when I'm at home.

**Comment by pbek** [comment]
But unrelated the the problem there is another issue (in QON) where the line numbers are off the center for higher lines (like headlines).

This was your PR:

Screenshot_20210630_103827

And in this PR it's even worse:

Screenshot_20210630_104111

**Comment by Waqar144** [comment]
Yes, this needs to fixed as well. Let me see..

**Pull request merged**
