### PR TITLE
Add css highlighting

### PR DESCRIPTION
**Pull request by Waqar144**

### CODE REVIEW

**Comment by Waqar144** [comment]
I am waiting to see what you think. This one took some time and _effort_ :sleepy: :laughing:

**Comment by pbek** [comment]
Haha, background-coloring of color values! Awesome! :laughing:

**Comment by pbek** [comment]
But now you need a complementary foreground color otherwise you can't see for example

```css
body {
   background-color: #000000;
}
```

in the light theme

**Comment by Waqar144** [comment]
> Haha, background-coloring of color values! Awesome! laughing

Looks kinda nice, right? Can come in handy I think.
It should highlight `#xxxxxx`, `color-name`, and `rgb(x,x,x)`

**Comment by Waqar144** [comment]
> But now you need a complementary foreground color otherwise you can't see for example
> 
> ```css
> body {
>    background-color: #000000;
> }
> ```
> 
> in the light theme

Yes.. that's true. For black, I will set the foreground to white... Though there are a lot of colors that are close to black... I wonder if there is a color inversion function..

**Comment by pbek** [comment]
https://doc.qt.io/qt-5/qimage.html#invertPixels would possibly be a (slow) way

**Comment by pbek** [comment]
https://stackoverflow.com/questions/6961725/algorithm-for-calculating-inverse-color sounds great

**Comment by pbek** [comment]
> https://stackoverflow.com/questions/6961725/algorithm-for-calculating-inverse-color

But it is getting tricky for colors close to an even grey... then the formula will produce the same color again

**Comment by Waqar144** [comment]
> > https://stackoverflow.com/questions/6961725/algorithm-for-calculating-inverse-color
> 
> But it is getting tricky for colors close to an even grey... then the formula will produce the same color again

Now I see why a lot of editors don't do it :rofl:

I will find a way.. though I am not so sure about this right now.

I wish there was a way to apply `<` with colors

**Comment by pbek** [comment]
PhpStorm simply adds a (or multiple) dots with the color left of the line where the color appears. You can also select a new color there (color picker). :grin: (for us: `Ctrl + Click` on color shows a color picker? :laughing: )

**Comment by Waqar144** [comment]
> PhpStorm simply adds a (or multiple) dots with the color left of the line where the color appears. You can also select a new color there (color picker).

kind of like VsCode 

grin (for us: `Ctrl + Click` on color shows a color picker? laughing )

Sounds implementable :grin:

**Comment by pbek** [comment]
> I will find a way.. though I am not so sure about this right now.

It is getting harder the more ways of coding colors you are supporting. Codes like `#123456` are just one way of many. :grin: 

`#123456` just means 0x12 red, 0x34 blue and 0x56 green. 0x00 is min. 0xFF is max.

**Comment by Waqar144** [comment]
> > I will find a way.. though I am not so sure about this right now.
> 
> It is getting harder the more ways of coding colors you are supporting. Codes like `#123456` are just one way of many. grin
> 
> `#123456` just means 0x12 red, 0x34 green and 0x56 blue. 0x00 is min. 0xFF is max.

We already support three ways of color coding... 

Color inversion is going to result in multiple color combinations. May look ugly in certain circumstances.

**Comment by pbek** [comment]
> Color inversion is going to result in multiple color combinations. May look ugly in certain circumstances.

You need a complementary color.

**Comment by smokris** [comment]
> But it is getting tricky for colors close to an even grey... then the formula will produce the same color again […] Color inversion is going to result in multiple color combinations. May look ugly in certain circumstances.

Perhaps select either the plain text color or the plain text background color, whichever has greater contrast from the highlighted CSS color?  Something like this:

    QColor plainTextForegroundColor = _formats[NoState].foreground();
    QColor plainTextBackgroundColor = _formats[NoState].background();
    int contrastFromForeground = abs(plainTextForegroundColor.lightness() - c.lightness());
    int contrastFromBackground = abs(plainTextBackgroundColor.lightness() - c.lightness());
    if (contrastFromForeground > contrastFromBackground)
        f.setForeground(plainTextForegroundColor);
    else
        f.setForeground(plainTextBackgroundColor);

**Comment by Waqar144** [comment]
@smokris thanks. That helped a lot.

**Pull request merged**
