### PR TITLE
Highlight emphasis/strong at the end

### PR DESCRIPTION
**Pull request by Waqar144**
~~Should fix pbek/QOwnNotes#2952~~
Should fix pbek/QOwnNotes#2972

Didn't test it a lot so there might still be issues

### CODE REVIEW

**Comment by pbek** [comment]
Thank you very much!
But I tested the example in QOwnNotes:


~~~markdown
```
(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
```

    (?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])

`(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])`
~~~

And it still showed my note folder URL in the preview...

**Comment by pbek** [comment]
image

**Comment by Waqar144** [comment]
Yeah I am not sure if fixing those is very practical atm given there is no way to know about regressions and they seem like extreme cases

**Comment by pbek** [comment]
Yeah, would have regressions for sure! 😬

Which markdown should I test your PR against?

**Comment by Waqar144** [comment]
Linked the wrong ticket, it is addressing: https://github.com/pbek/QOwnNotes/issues/2972
So the markdowns in that ticket should be okay now.

**Comment by pbek** [comment]
I really dislike the automatic issue closing, when you merge a PR. Both issues were closed now.

**Comment by Waqar144** [comment]
At least it shouldn't work if the repo is different lol. Does this mean we can close issues anywhere on github?

**Comment by pbek** [comment]
I guess not. **I** closed it when I merged the PR... But there is no way around that, maybe one needs to remove the link to the issue from the first (?) comment...

**Comment by Waqar144** [comment]
probably

**Pull request merged**
