### PR TITLE
Fix formatting in headings

### PR DESCRIPTION
**Pull request by Waqar144**
fixing my own stupidity lol

I wonder why no one has noticed it yet :thinking:

### CODE REVIEW

**Comment by pbek** [comment]
What does this PR fix?

**Comment by pbek** [comment]
And can you please also submit a PR that fixes **my** own stupidity? Maybe we should make a product out of that fix. :laughing:

**Comment by Waqar144** [comment]
> What does this PR fix?

The italics, bolds and links aren't being formatted correctly in headings. Try this:

```md
# Heading 1 *this is italic* [link](http://this-is-a-really-long-long-long-link.commmmmm) *again italic* and now finishing with some **bold text** , *ok* bye
```

All because, instead of `capturedLength()`, I for some reason used `capturedEnd()` in `setFormat()`

And can you please also submit a PR that fixes my own stupidity? Maybe we should make a product out of that fix. laughing

:rofl:

**Comment by pbek** [comment]
> # Heading 1 *this is italic* [link](http://this-is-a-really-long-long-long-link.commmmmm) *again italic* and now finishing with some **bold text** , *ok* bye

Saw that. Didn't have the time to take a look at it. :)

**Comment by pbek** [comment]
The link is highlighted in blue instead of orange in QOwnNotes, what colors are you using there?

image

**Comment by Waqar144** [comment]
> The link is highlighted in blue instead of orange in QOwnNotes, what colors are you using there?
> 
> image

I just took the colors from predefined rules.

**Comment by pbek** [comment]
Then there is no integration for QOwnNotes schema colors yet? Because the link color is orange in my schema.

**Comment by Waqar144** [comment]
> Then there is no integration for QOwnNotes schema colors yet? Because the link color is orange in my schema.

:grimacing:

will be fixed in a moment

**Pull request merged**
